### ISSUE TITLE
Method of checking compatibility of jailbreaks causes some quirks

### ISSUE THREAD

**Issue by hopolapopola** [mass1ve-err0r/CanIJailbreak2-Website#4]
It seems that using a range bound by a min and max supported version leads to misleading information at times, which I noticed with Unc0ver. For this tool, it does not support 12.5-12.5.1, only checkra1n and Chimera do, but it does (officially) support 11-12.4.8 and 13-13.5. I haven't checked but there might be more minor errors like this for some of the other tools.

**Comment by mass1ve-err0r** [comment]
Hey!
Thanks for reporting. I haven't implemented a solution to that just yet, however I do have an idea how to solve that:
Splitting the supported version field based on CPU subtype (essentially extend the dictionaries to contain arm64e and arm64 fields with corresponding ranges).

It's a trivial fix but not pushed onto git, still have some testing todo and other stuff on the agenda lmao

EDIT 1:
spelling.

**Comment by mass1ve-err0r** [comment]
fixed with notes / hints, see V2 notes when commits are pushed later
