### ISSUE TITLE
Is API available to public?

### ISSUE THREAD

**Issue by Qerope** [mass1ve-err0r/CanIJailbreak2-Website#9]
"THIS ENDPOINT REQUIRES AUTHENTICATION" what does this mean? Can I use the API? If not, what are the conditions?

**Comment by mass1ve-err0r** [comment]
API requires a token, what's your use-case for it?

**Comment by Qerope** [comment]
Personal use only. I was looking for a reliable source to get information about new jailbreaking tools release.

**Comment by mass1ve-err0r** [comment]
In that case I'd recommend either running your own instance or visiting the site every now & then.

Personal use is outside of the scope for an official token.
